# Generated by Django 4.1.7 on 2023-02-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('COLLEGE', 'College'), ('CODING BOOTCAMP', 'Coding Bootcamp'), ('ONLINE COURSE', 'Online Course')], max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('WEB DEVELOPMENT', 'Web Development'), ('FIGMA', 'Figma'), ('APPLICATION', 'Application'), ('MOBILE', 'Mobile Application')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/files')),
                ('git_hub_link', models.CharField(max_length=250)),
                ('project_link', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
